<?php


namespace App\Model\Table;
use Cake\ORM\Table;

class AccountsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->setTable('accounts');
        $this->setPrimaryKey('id');
    }
}